# Generated by Django 5.1.7 on 2025-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='top_post',
            field=models.BooleanField(default=False),
        ),
    ]
