# Generated by Django 5.1.7 on 2025-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('Authintro', models.TextField()),
            ],
        ),
    ]
