# Generated by Django 5.1.7 on 2025-12-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='blog.userprofile'),
        ),
    ]
