# Generated by Django 5.1.7 on 2026-01-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('post', 'Post')], default='article', max_length=10),
        ),
    ]
