# Generated by Django 5.1.7 on 2026-01-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='blog.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='blog_conten_article_c0adf7_idx')],
            },
        ),
    ]
